version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /home/log:/log
    ports:
      - "8080:8080"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /home/gcp_haeun/wooahgong_config/wooahgong.conf:/etc/nginx/conf.d/default.conf 
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   ports:
  #     - "80:80"
  #     - "443:443"

  # bigdata:
  #   build:
  #     context: ./bigdata
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"

# networks:
#   default:
#     external:
#       name: wooahgong_network