version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /home/haeun/wooahgong/upload_images:/upload_images
    ports:
      - "8080:8080"
    networks:
      - wooahgong_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /home/haeun/wooahgong/build:/build
    networks:
      - wooahgong_network

  bigdata:
    build:
      context: ./bigdata
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - wooahgong_network

networks:
  wooahgong_network:
    driver: bridge