# 이미지 태그 설정
FROM node:16.14.0-alpine as build-stage
# WORKDIR /homepage
# COPY . .
# RUN npm install
# RUN npm run build

# FROM nginx:stable-alpine as production-stage
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./nginx.conf /etc/nginx/conf.d/nginx.conf
# COPY --from=build-stage ./homepage/build /usr/share/nginx/html/homepage
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

